### ISSUE TITLE
evaluation fails

### ISSUE THREAD

**Issue by symphorien** [angr/nixpkgs#2]
```commands
$ nix-shell --arg ANGR_NIXPKGS_PATH $(readlink -f .) 
error: anonymous function at /home/symphorien/src/angr-nixpkgs/pkgs/python-modules/angr/default.nix:1:1 called without required argument 'cppheaderparser', at /nix/store/kbh58v7li4chxmzm4xs2ar9hy4784668-nixos-20.03.3087.b4db68ff563/nixos/lib/customisation.nix:69:16
(use '--show-trace' to show detailed location information)
```

**Comment by symphorien** [comment]
43801e93154e29602a8b5fcba2c89ec2aaf3d1fb is the first bad commit
commit 43801e93154e29602a8b5fcba2c89ec2aaf3d1fb
Author: Pamplemousse <xav.maso@gmail.com>
Date:   Thu Oct 1 10:46:59 2020 -0700

    python3Packages.angr: 8.20.6.1 -> 9.0.4446
    
    Signed-off-by: Pamplemousse <xav.maso@gmail.com>

 pkgs/python-modules/angr/default.nix | 17 +++++++++++++----
 1 file changed, 13 insertions(+), 4 deletions(-)

**Comment by ltfish** [comment]
We did add `cppheaderparser` as a dependency! @Pamplemousse do you want to fix the nixOS package?

**Comment by Pamplemousse** [comment]
Sorry @ltfish, I was a bit slow to answer.

@symphorien, thanks for reporting!

`CppHeaderParser` has been added to `nixpkgs` very recently: See NixOS/nixpkgs#99206 .
Due to the speed of the release process (particularly of the builds on Hydra), it might lag behind the GitHub repository by a couple of days; And hence `python3Packages.cppheaderparser` might not yet be available on the unstable channel...

(if you don't use the `unstable` channel, it won't work - because stable channels do not receive all the packages updates)

Two solutions:
1. Wait 'til `unstable` catches up;
2. Use a local `nixpkgs`; As far as I remember, here is what I have:
```shell
git clone git@github.com:NixOS/nixpkgs.git --depth 1 ~/nixpkgs

# put this in `~/.<YOUR SHELL>rc` to make it persistent
[ -d "${HOME}/nixpkgs/" ] && NIX_PATH="nixpkgs=${HOME}/nixpkgs/:${NIX_PATH}"
```

**Comment by Pamplemousse** [comment]
@symphorien , more info about channels, and how to use packages from `master` while keeping the rest of your system on `unstable` can be found here: https://nixos.wiki/wiki/Nix_channels#When_unstable_lags_behind_master .

**Comment by symphorien** [comment]
Ok thanks.

I think the README deserves a note that the repo depends on nixpkgs-unstable. Especially since I thought this was a fork of nixpkgs (given the repo name) and not a sort of overlay on top of it.
